DB_FAISS_PATH: "vectorstores/db_faiss"
custom_prompt_template: |
  Use the following pieces of information to answer the user's question. If you don't know the answer, just say that you don't know the answer, don't try to make up an answer.

  Context: {context}
  Question: {question}

  Only returns the helpful answer below and nothing else.
  Helpful answer.
